from collections import namedtuple
import sys

fdata = namedtuple('fdata', 'num_indices, min_arity, max_arity')

func_symbols = {'Equals': fdata(0, 2, 2),
                'Not': fdata(0, 1, 1),
                'Ite': fdata(0, 3, 3),
                'Sub': fdata(0, 2, 2),
                'Add': fdata(0, 2, sys.maxsize),
                'LT': fdata(0, 2, 2),
                'GT': fdata(0, 2, 2),
                'LEQ': fdata(0, 2, 2),
                'GEQ': fdata(0, 2, 2),
                'Extract': fdata(2, 1, 1),
                'Concat': fdata(0, 2, 2),
                'Zero_extend': fdata(0, 2, 2),
                'BVAnd': fdata(0, 2, 2),
                'BVOr': fdata(0, 2, 2),
                'BVXor': fdata(0, 2, 2),
                'BVAdd': fdata(0, 2, 2),
                'BVSub': fdata(0, 2, 2),
                'BVMul': fdata(0, 2, 2),
                'BVUdiv': fdata(0, 2, 2),
                'BVUrem': fdata(0, 2, 2),
                'BVShl': fdata(0, 2, 2),
                'BVAshr': fdata(0, 2, 2),
                'BVLshr': fdata(0, 2, 2),
                'BVUlt': fdata(0, 2, 2),
                'BVUle': fdata(0, 2, 2),
                'BVUgt': fdata(0, 2, 2),
                'BVUge': fdata(0, 2, 2),
                'BVSlt': fdata(0, 2, 2),
                'BVSle': fdata(0, 2, 2),
                'BVSgt': fdata(0, 2, 2),
                'BVSge': fdata(0, 2, 2),
                'BVNot': fdata(0, 1, 1),
                'BVNeg': fdata(0, 1, 1),
                'No_op': fdata(0, 0, 0), }
